"""Kernel protocols — interface placeholders (depth A)."""

from __future__ import annotations

from typing import Any, Protocol


class Kernel(Protocol):
    def boot(self) -> None: ...
    def shutdown(self) -> None: ...
    def handle_turn(self, turn_input: Any) -> Any: ...
    def register_capability(self, kind: str, handler: Any) -> None: ...
