"""Layer protocols — interface placeholders (depth A)."""

from __future__ import annotations

from typing import Any, Protocol


class ContextLayer(Protocol):
    def build_context(self, turn: Any) -> Any: ...
    def trim_context(self, context: Any, budget: int) -> Any: ...


class OrchestrationLayer(Protocol):
    def plan(self, goal: str, context: Any) -> Any: ...
    def next_step(self, state: Any) -> Any: ...
    def run_loop(self, loop_def: Any) -> Any: ...
    def run_graph(self, graph_def: Any) -> Any: ...


class ActionLayer(Protocol):
    def execute_action(self, plan_step: Any) -> Any: ...
    def request_approval(self, action: Any) -> bool: ...
